emotion/urls.py
from django.urls import path
from . import views

app_name = 'emotion'

urlpatterns = [
    path('', views.emotion_analysis, name="emotion_anaylsis"),
    path('type/', views.emotion_analysis_type, name="emotion_analysis_type"),
    path('import/', views.emotion_analysis_import, name="emotion_analysis_import"),
]

sentiment/urls.py
from django.urls import path
from . import views


app_name = 'sentiment'

urlpatterns = [
    path('', views.sentiment_analysis, name="sentiment_anaylsis"),
    path('type/', views.sentiment_analysis_type, name="sentiment_analysis_type"),
    path('import/', views.sentiment_analysis_import, name="sentiment_analysis_import"),
    path('search/', views.search_tweets, name='search_tweets'),
]

sentiment_emotion_analysis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sentiment/', include('sentiment.urls')),
    path('', include('sentiment_or_emotion.urls')),
    path('emotion/', include('emotion.urls')),
]

sentiment/models.py
from django.db import models 

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from pyarabic.araby import strip_tashkeel,tokenize





def preprocess_text(text):
    normalized_text = strip_tashkeel(text)
    tokens = tokenize(normalized_text)
    preprocessed_text = ' '.join(tokens)
    return preprocessed_text

def create_and_train_svm_model(data_path):
    # Load data
    data = pd.read_excel(data_path)

    # Preprocess text data
    data["preprocessed_text"] = data["Feed"].apply(preprocess_text)

    # Split data into train and test sets
    X_train, X_test, y_train, y_test = train_test_split(data["preprocessed_text"], data["Sentiment"], test_size=0.2, random_state=42)

    # Create TF-IDF vectorizer
    vectorizer = TfidfVectorizer(max_features=1000)

    # Train the vectorizer on training data
    vectorizer.fit(X_train)

    # Transform data into TF-IDF vectors
    X_train_tfidf = vectorizer.transform(X_train)
    X_test_tfidf = vectorizer.transform(X_test)

    # Create and train the SVM model
    svm_model = SVC(kernel='linear')
    svm_model.fit(X_train_tfidf, y_train)

    return svm_model, vectorizer


class Tweet(models.Model):
    text = models.TextField()
    
    def __str__(self):
        return self.text

sentiment/forms.py
from django import forms

class Sentiment_Typed_Tweet_analyse_form(forms.Form):
    sentiment_typed_tweet = forms.CharField(initial='nothing')

class Sentiment_Imported_Tweet_analyse_form(forms.Form):
    sentiment_imported_tweet = forms.CharField(initial='nothing')

sentiment/views.py
from django.shortcuts import render, redirect, HttpResponse
from .forms import Sentiment_Typed_Tweet_analyse_form
from .forms import Sentiment_Imported_Tweet_analyse_form
from .tweepy_sentiment import Import_tweet_sentiment
from collections import Counter

from .models import Tweet
from pyarabic.araby import strip_tashkeel, normalize_hamza
from .preprocces import shakl, alif

from .camel_model import sentiment_analysis_code as camel
from .regretion_model import sentiment_analysis_code as regretion
from .rcnn_model import sentiment_analysis_code as rcnn
from .svm_model import sentiment_analysis_code as svm
from .naive_model import sentiment_analysis_code as naive
def preprocess_text(text):
    text = shakl(text)
    text = alif(text)
    return text

    
def sentiment_analysis(request):
    return render(request, 'home/sentiment.html')

def sentiment_analysis_type(request):
    if request.method == 'POST':
        form = Sentiment_Typed_Tweet_analyse_form(request.POST)
        model = request.POST.get('model', '')
        #analyse = regretion()
        print(model)
        if model == 'Camel':
            analyse = camel()
        elif model == 'Rcnn':
            analyse = rcnn()
        elif model == 'Svm':    
            analyse = svm() 
        elif model == 'Naive Bayes':    
            analyse = naive() 
        else :
            analyse = regretion()
        if form.is_valid():
            tweet = form.cleaned_data['sentiment_typed_tweet']
            sentiment = analyse.get_tweet_sentiment(tweet)
            args = {'tweet':tweet, 'sentiment':sentiment , 'model': model}
            return render(request, 'home/sentiment_type_result.html', args)

    else:
        form = Sentiment_Typed_Tweet_analyse_form()
        return render(request, 'home/sentiment_type.html')

def sentiment_analysis_import(request):
    if request.method == 'POST':
        form = Sentiment_Imported_Tweet_analyse_form(request.POST)
        tweet_text = Import_tweet_sentiment()
        analyse = regretion()

        if form.is_valid():
            handle = form.cleaned_data['sentiment_imported_tweet']

            if handle[0]=='#':
                list_of_tweets = tweet_text.get_hashtag(handle)
                list_of_tweets_and_sentiments = []
                for i in list_of_tweets:
                    list_of_tweets_and_sentiments.append((i,analyse.get_tweet_sentiment(i)))
                args = {'list_of_tweets_and_sentiments':list_of_tweets_and_sentiments, 'handle':handle}
                return render(request, 'home/sentiment_import_result_hashtag.html', args)

            list_of_tweets = tweet_text.get_tweets(handle)
            list_of_tweets_and_sentiments = []
            if handle[0]!='@':
                handle = str('@'+handle)
            for i in list_of_tweets:
                list_of_tweets_and_sentiments.append((i,analyse.get_tweet_sentiment(i)))
            args = {'list_of_tweets_and_sentiments':list_of_tweets_and_sentiments, 'handle':handle}
            return render(request, 'home/sentiment_import_result.html', args)

    else:
        form = Sentiment_Imported_Tweet_analyse_form()
        return render(request, 'home/sentiment_import.html')



def search_tweets(request):
    query = request.GET.get('q', '')
    sentiment_counts = {'positive': 0, 'negative': 0, 'neutral': 0}
    total_sentiments = 0 
    
    model = request.GET.get('model', '')
    #analyse = regretion()
    
    if model == 'Camel':
            analyse = camel()
    elif model == 'Rcnn':
        analyse = rcnn()
    elif model == 'Svm':    
        analyse = svm() 
    elif model == 'Naive Bayes':    
            analyse = naive() 
    else :
        analyse = regretion()
    
    if query:
        processed_query = preprocess_text(query)
        matching_tweets = Tweet.objects.filter(text__icontains=processed_query)
        sentiments = [analyse.get_tweet_sentiment(preprocess_text(tweet.text)) for tweet in matching_tweets]
        sentiment_counts = Counter(sentiments)
        total_sentiments = sum(sentiment_counts.values()) 
    return render(request, 'search_tweets.html', {
        'query': query,
        'sentiment_counts': sentiment_counts,
        'total_sentiments': total_sentiments,
        'model': model
    })

sentiment/templates/search_tweets.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>
    <title>Sentiment Analysis of Imported Tweet</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,300,500" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'home/css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/jquery.timepicker.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">

    <!-- searchbox css -->
    <link rel="stylesheet" href="{% static 'type/css/searchbox.css' %}">

    <!-- icons -->
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <!-- insertion templates -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">        
  	<link rel="stylesheet" href="{% static 'insertion/css/tooplate-style.css' %}">
  	<link rel="stylesheet" href="{% static 'insertion/css/fontawesome-all.min.css' %}"> 

<!-- lapsus static -->
    <link href="{% static 'lapsus/css/font-awesome.min.css' %}" rel="stylesheet">   
    <!-- Custom CSS -->
    <link href="{% static 'lapsus/css/style.css' %}" rel="stylesheet">


</head>
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar" data-aos="fade-down" data-aos-delay="500">
      <div class="container">
        <a class="navbar-brand" href="/">Home</a>
        <div class="collapse navbar-collapse" id="ftco-nav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a href="/sentiment" class="nav-link">Sentiment Analysis</a></li>
           
          </ul>
        </div>
      </div>
    </nav>
    <!-- END nav -->

    <section class="ftco-cover"  id="section-home" style="background-image: url({% static 'home/images/data.jpg' %}); background-attachment: scroll;"  data-aos="fade"  data-stellar-background-ratio="0.5">
      <div class="container">
        <div class="row align-items-center ftco-vh-100">
            <div class="col-7 mt-10 grid">
                <div>
                    <h1 class="ftco-heading mb-3" data-aos="fade-up" data-aos-delay="500">Sentiment Overview</h1>
                    <h2 class="h5 ftco-subheading" data-aos="fade-up"  data-aos-delay="600">Search about subject to import tweets abou it and do sentiment analysis</h2>
                    {% if model != '' %} <h3 class="h3 ftco-subheading"> By {{model}} model</h3>{% endif %}
                    <div class="row">
                        {% if sentiment_counts.Positive > sentiment_counts.Negative %}
                            <div class="box counter-left md-5 col-2" data-aos="fade-up" data-aos-delay="700">
                                <img src="{% static 'icons/combo_positive_glow.png' %}">
                            </div>
                        {% endif %}

                        {% if sentiment_counts.Positive == sentiment_counts.Negative %}
                            <div class="box counter-left md-5 col-2" data-aos="fade-up" data-aos-delay="700">
                                <img src="{% static 'icons/combo_neutral_glow.png' %}">
                            </div>
                        {% endif %}

                        {% if sentiment_counts.Positive < sentiment_counts.Negative %}
                            <div class="box counter-left md-5 col-2" data-aos="fade-up" data-aos-delay="700">
                                <img src="{% static 'icons/combo_negative_glow.png' %}">
                            </div>
                        {% endif %}

                    </div>
                    <br>
                    <br>
                    {% block content %}
                        <div class="page" data-aos="fade-up" data-aos-delay="800">
                            <div class="page__demo">
                                    
                                <form class="search" method="get" ction="{% url 'sentiment:search_tweets' %}">
                                    {% csrf_token %}
                                    <div class="a-field search__field">
                                        <select name='model'>
                                            <option value="Camel" >Camel</option>
                                            <option value="Logistic Regression">Logistic Regression</option>
                                            <option value="Rcnn">Rcnn</option>
                                            <option value="Svm">Svm</option>
                                            <option value='Naive Bayes'>Naive Bayes</option>

                                            
                                        </select>
                                        <input type="text" id="sentiment_imported_tweet" name="q" class="r-text-field a-field__input search__input" placeholder="Enter a word..." value="{{ query }}" required>
                                        <label class="a-field__label-wrap search__hint" for="query"></label>        
                                    </div>
                                    <button class="r-button search__button search__submit" type="submit">
                                        <span class="search__submit-label">Search</span>
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 56.966 56.966" class="search__icon search__icon-search">
                                        <path d="M55.146 51.887L41.588 37.786A22.926 22.926 0 0 0 46.984 23c0-12.682-10.318-23-23-23s-23 10.318-23 23 10.318 23 23 23c4.761 0 9.298-1.436 13.177-4.162l13.661 14.208c.571.593 1.339.92 2.162.92.779 0 1.518-.297 2.079-.837a3.004 3.004 0 0 0 .083-4.242zM23.984 6c9.374 0 17 7.626 17 17s-7.626 17-17 17-17-7.626-17-17 7.626-17 17-17z"/>
                                        </svg>
                                    </button>
                                </form>
                            </div>
                        </div>
                        {% if query %}
                            <h3 class="text-light mb-3 mt-5" >Sentiment Analysis Results for "{{ query }}":</h3>
                            <ul class="">
                                <li class="text-light ">All: {{ total_sentiments }}</li>
                                <li class="text-light ">Positive: {{ sentiment_counts.Positive }}</li>
                                <li class="text-light ">Negative: {{ sentiment_counts.Negative }}</li>
                                <li class="text-light ">Neutral: {{ sentiment_counts.Neutral }}</li>
                            </ul>
                        {% else %}
                        {% endif %}
                    {% endblock %}
                </div>   
                
            </div>
            <div class="col">
                <canvas id="sentimentPieChart"></canvas>
            </div>
        </div>
      </div>
         
           
    </section>
    <!-- END section -->





  


  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static 'register/js/jquery.min.js' %}"></script>
  <script src="{% static 'register/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'register/js/popper.min.js' %}"></script>
  <script src="{% static 'register/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'register/js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'register/js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'register/js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'register/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'register/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'register/js/aos.js' %}"></script>
  <script src="{% static 'register/js/jquery.animateNumber.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'register/js/google-map.js' %}"></script>
  <script src="{% static 'register/js/main.js' %}"></script>
    <script src="{% static 'register/othertemplate/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'register/othertemplate/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'register/othertemplate/js/main.js' %}"></script>

    <!-- insertion static -->

    <!-- <script src="{% static 'insertion/js/jquery-3.2.1.slim.min.js' %}"></script> -->

    <!-- lapsus static -->
    
    <script src="{% static 'lapsus/js/jquery.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'lapsus/js/bootstrap.min.js' %}"></script>
    <!-- Respond JS for IE8 -->
    <script src="{% static 'lapsus/js/respond.min.js' %}"></script>
    <!-- HTML5 Support for IE -->
    <script src="{% static 'lapsus/js/html5shiv.js' %}"></script>
    <!-- Custom JS -->
    <script src="{% static 'lapsus/js/custom.js' %}"></script>

    <!-- searchbox type js -->
    <script src="{% static 'type/js/search_box.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0"></script>


    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var ctx = document.getElementById('sentimentPieChart').getContext('2d');
            var sentimentPieChart = new Chart(ctx, {
                plugins: [ChartDataLabels], // Ensure the plugin is registered
                type: 'pie',
                data: {
                    labels: ['Positive', 'Negative', 'Neutral'],
                    datasets: [{
                        label: 'Sentiment Analysis',
                        data: [{{ sentiment_counts.Positive }}, {{ sentiment_counts.Negative }}, {{ sentiment_counts.Neutral }}], // Dynamic data
                        backgroundColor: [
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(255, 206, 86, 0.2)'
                        ],
                        borderColor: [
                            'rgba(75, 192, 192, 1)',
                            'rgba(255, 99, 132, 1)',
                            'rgba(255, 206, 86, 1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    responsive: true,
                    plugins: {
                        datalabels: {
                            color: '#fff',
                            backgroundColor: '#666', // Optional: adds background to the labels for better visibility
                            borderRadius: 3,
                            padding: 6,
                            font: {
                                weight: 'bold'
                            },
                            formatter: (value, ctx) => {
                                const total = ctx.dataset.data.reduce((a, b) => a + b, 0);
                                const percentage = (value / total * 100).toFixed(1) + "%";
                                return percentage;
                            }
                        }
                    }
                }
            });
        });
        </script>
        

  </body>
</html> 